FROM eclipse-temurin:17-jdk-alpine
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH
WORKDIR $HOME/app
COPY --chown=user . $HOME/app
COPY target/*.jar app.jar
EXPOSE 8181
CMD ["java", "-jar", "app.jar"]